Repository FromDoppler/doppler-contact-policies-api, pull requests merged in 2021-07, with the labels that each got.

#23 Refactor find user
  Doppler.ContactPolicies.Api.Test/Authorization.cs
  Doppler.ContactPolicies.Api.Test/GetContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Api/Controllers/ContactPolicies.cs
  Doppler.ContactPolicies.Business.Logic/Extensions/MapperExtension.cs
  Doppler.ContactPolicies.Business.Logic/Services/ContactPoliciesService.cs
  Doppler.ContactPolicies.Business.Logic/Services/IContactPoliciesService.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/ContactPoliciesSettingsRepository.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/IContactPoliciesSettingsRepository.cs
Labels: size/M

#24 Refactor account name by id user
  Doppler.ContactPolicies.Api.Test/Authorization.cs
  Doppler.ContactPolicies.Api.Test/GetContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Api/Controllers/ContactPolicies.cs
  Doppler.ContactPolicies.Business.Logic.Test/ContactPoliciesServiceTest.cs
  Doppler.ContactPolicies.Business.Logic/Services/ContactPoliciesService.cs
  Doppler.ContactPolicies.Business.Logic/Services/IContactPoliciesService.cs
  Doppler.ContactPolicies.Data.Access/Entities/ContactPoliciesSettings.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/ContactPoliciesSettingsRepository.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/IContactPoliciesSettingsRepository.cs
Labels: size/L

#25 [No task] Include logger in api
  Doppler.ContactPolicies.Api/Doppler.ContactPolicies.Api.csproj
  Doppler.ContactPolicies.Api/Logging/LogglySetup.cs
  Doppler.ContactPolicies.Api/Logging/SerilogSetup.cs
  Doppler.ContactPolicies.Api/Program.cs
Labels: size/M

#27 chore: add CORS
  Doppler.ContactPolicies.Api/Startup.cs
Labels: size/S

#26 Add test for update contact policies
  Doppler.ContactPolicies.Api.Test/Authorization.cs
  Doppler.ContactPolicies.Api.Test/GetContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Api.Test/UpdateContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/ContactPoliciesSettingsRepository.cs
Labels: size/L

#31 Integration users api
  Doppler.ContactPolicies.Api.Test/UpdateContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Api/Controllers/ContactPolicies.cs
  Doppler.ContactPolicies.Api/Startup.cs
  Doppler.ContactPolicies.Api/appsettings.Development.json
  Doppler.ContactPolicies.Api/appsettings.json
  Doppler.ContactPolicies.Business.Logic.Test/ContactPoliciesServiceTest.cs
  Doppler.ContactPolicies.Business.Logic.Test/UserFeaturesServiceTest.cs
  Doppler.ContactPolicies.Business.Logic/DTO/Features.cs
  Doppler.ContactPolicies.Business.Logic/Doppler.ContactPolicies.Business.Logic.csproj
  Doppler.ContactPolicies.Business.Logic/Services/UserFeaturesServiceSettings.cs
  Doppler.ContactPolicies.Business.Logic/UserApiClient/Handlers/TokenHandler.cs
  Doppler.ContactPolicies.Business.Logic/UserApiClient/Services/IUserFeaturesService.cs
  Doppler.ContactPolicies.Business.Logic/UserApiClient/Services/UserFeaturesService.cs
  Doppler.ContactPolicies.Business.Logic/UserApiClient/UsersApiServiceCollectionExtensions.cs
Labels: size/L
