Repository FromDoppler/doppler-contact-policies-api, pull requests merged in 2021-06, with the labels that each got.

#1 Fb base scaffolding
  ContactPoliciesApi.sln
  Doppler.Contact.Policies.Api.Test/Doppler.Contact.Policies.Api.Test.csproj
  Doppler.Contact.Policies.Api.Test/UnitTest1.cs
  Doppler.Contact.Policies.Business.Logic.Test/Doppler.Contact.Policies.Business.Logic.Test.csproj
  Doppler.Contact.Policies.Business.Logic.Test/UnitTest1.cs
  Doppler.Contact.Policies.Business.Logic/Class1.cs
  Doppler.Contact.Policies.Business.Logic/Doppler.Contact.Policies.Business.Logic.csproj
  Doppler.Contact.Policies.Data.Access.Test/Doppler.Contact.Policies.Data.Access.Test.csproj
  Doppler.Contact.Policies.Data.Access.Test/UnitTest1.cs
  Doppler.Contact.Policies.Data.Access/Class1.cs
  Doppler.Contact.Policies.Data.Access/Doppler.Contact.Policies.Data.Access.csproj
  doppler-contact-policies-api/Doppler.Contact.Policies.Api.csproj
Labels: size/L

#3 Fb base scaffolding
  .gitattributes
  .gitignore
  ContactPoliciesApi.sln
  Doppler.Contact.Policies.Api.Test/Doppler.Contact.Policies.Api.Test.csproj
  Doppler.Contact.Policies.Api.Test/UnitTest1.cs
  Doppler.Contact.Policies.Business.Logic.Test/Doppler.Contact.Policies.Business.Logic.Test.csproj
  Doppler.Contact.Policies.Business.Logic.Test/UnitTest1.cs
  Doppler.Contact.Policies.Business.Logic/Class1.cs
  Doppler.Contact.Policies.Business.Logic/Doppler.Contact.Policies.Business.Logic.csproj
  Doppler.Contact.Policies.Data.Access.Test/Doppler.Contact.Policies.Data.Access.Test.csproj
  Doppler.Contact.Policies.Data.Access.Test/UnitTest1.cs
  Doppler.Contact.Policies.Data.Access/Class1.cs
  Doppler.Contact.Policies.Data.Access/Doppler.Contact.Policies.Data.Access.csproj
  README.md
  doppler-contact-policies-api/Controllers/WeatherForecastController.cs
  doppler-contact-policies-api/Doppler.Contact.Policies.Api.csproj
  doppler-contact-policies-api/Program.cs
  doppler-contact-policies-api/Properties/launchSettings.json
  doppler-contact-policies-api/Startup.cs
  doppler-contact-policies-api/WeatherForecast.cs
  doppler-contact-policies-api/appsettings.Development.json
  doppler-contact-policies-api/appsettings.json
Labels: size/XL

#4 chore: add base validation and format files
  .config/dotnet-tools.json
  .dockerignore
  .doppler-ci
  .editorconfig
  .gitattributes
  .github/dependabot.yml
  .gitignore
  .gitlint
  .prettierignore
  ContactPoliciesApi.sln
  Dockerfile
  Doppler.Contact.Policies.Api/Controllers/WeatherForecastController.cs
  Doppler.Contact.Policies.Api/Doppler.Contact.Policies.Api.csproj
  Doppler.Contact.Policies.Api/Program.cs
  Doppler.Contact.Policies.Api/Properties/launchSettings.json
  Doppler.Contact.Policies.Api/Startup.cs
  Doppler.Contact.Policies.Api/WeatherForecast.cs
  Doppler.Contact.Policies.Api/appsettings.Development.json
  Doppler.Contact.Policies.Api/appsettings.json
  Doppler.Contact.Policies.Api/wwwroot/favicon.ico
  Doppler.Contact.Policies.Api/wwwroot/robots.txt
  Doppler.Contact.Policies.Business.Logic/Class1.cs
  Doppler.Contact.Policies.Data.Access/Class1.cs
  Jenkinsfile
  build-n-publish.sh
  demo.http
  gitlint.sh
  package.json
  verify-w-docker.sh
  yarn.lock
Labels: size/XXL

#10 Add api base url for Swagger server configuration
  Doppler.Contact.Policies.Api/Startup.cs
Labels: size/XS

#11 Authorization doppler security
  .editorconfig
  .gitattributes
  .prettierignore
  Doppler.Contact.Policies.Api.Test/Authorization.cs
  Doppler.Contact.Policies.Api.Test/Doppler.Contact.Policies.Api.Test.csproj
  Doppler.Contact.Policies.Api/Controllers/ContactPolicies.cs
  Doppler.Contact.Policies.Api/Controllers/WeatherForecastController.cs
  Doppler.Contact.Policies.Api/Doppler.Contact.Policies.Api.csproj
  Doppler.Contact.Policies.Api/DopplerSecurity/ConfigureDopplerSecurityOptions.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/DopplerAuthorizationRequirement.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/DopplerSecurityDefaults.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/DopplerSecurityOptions.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/IsSuperUserAuthorizationHandler.cs
  Doppler.Contact.Policies.Api/DopplerSecurity/Policies.cs
  Doppler.Contact.Policies.Api/Program.cs
  Doppler.Contact.Policies.Api/Startup.cs
  Doppler.Contact.Policies.Api/WeatherForecast.cs
  Doppler.Contact.Policies.Api/appsettings.Development.json
  Doppler.Contact.Policies.Api/appsettings.json
  Doppler.Contact.Policies.Api/private-keys-dev/README.md
  Doppler.Contact.Policies.Api/private-keys-dev/dev.priv.key
  Doppler.Contact.Policies.Api/private-keys-dev/dev.priv.xml
  Doppler.Contact.Policies.Api/public-keys-dev/dev.pub.key
  Doppler.Contact.Policies.Api/public-keys-dev/dev.pub.xml
  Doppler.Contact.Policies.Api/public-keys/README.md
Labels: size/XL

#12 Add correct swagger endpoint URL
  Doppler.Contact.Policies.Api/Startup.cs
Labels: size/XS

#16 Naming general fixes
  build-n-publish.sh
  package.json
Labels: size/S

#18 Get contac policies dapper integration
  Doppler.ContactPolicies.Api.Test/Authorization.cs
  Doppler.ContactPolicies.Api.Test/Doppler.ContactPolicies.Api.Test.csproj
  Doppler.ContactPolicies.Api.Test/GetContactPoliciesSettingsTest.cs
  Doppler.ContactPolicies.Api.Test/UnitTest1.cs
  Doppler.ContactPolicies.Api/Controllers/ContactPolicies.cs
  Doppler.ContactPolicies.Api/Startup.cs
  Doppler.ContactPolicies.Api/appsettings.Development.json
  Doppler.ContactPolicies.Api/appsettings.json
  Doppler.ContactPolicies.Business.Logic.Test/ContactPoliciesServiceTest.cs
  Doppler.ContactPolicies.Business.Logic.Test/Doppler.ContactPolicies.Business.Logic.Test.csproj
  Doppler.ContactPolicies.Business.Logic.Test/UnitTest1.cs
  Doppler.ContactPolicies.Business.Logic/DTO/ContactPoliciesSettingsDto.cs
  Doppler.ContactPolicies.Business.Logic/Extensions/MapperExtension.cs
  Doppler.ContactPolicies.Business.Logic/Services/ContactPoliciesService.cs
  Doppler.ContactPolicies.Business.Logic/Services/IContactPoliciesService.cs
  Doppler.ContactPolicies.Data.Access/Core/DapperExtensions.cs
  Doppler.ContactPolicies.Data.Access/Core/DataBaseConnectionFactory.cs
  Doppler.ContactPolicies.Data.Access/Core/DopplerDataBaseSettings.cs
  Doppler.ContactPolicies.Data.Access/Core/IDatabaseConnectionFactory.cs
  Doppler.ContactPolicies.Data.Access/Core/IDopplerDataBaseSettings.cs
  Doppler.ContactPolicies.Data.Access/Doppler.ContactPolicies.Data.Access.csproj
  Doppler.ContactPolicies.Data.Access/Entities/ContactPoliciesSettings.cs
  Doppler.ContactPolicies.Data.Access/Entities/ExcludedSubscribersLists.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/ContactPoliciesSettingsRepository.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/IContactPoliciesSettingsRepository.cs
Labels: size/XL

#21 🚧 Insert contact policies
  Doppler.ContactPolicies.Api/Controllers/ContactPolicies.cs
  Doppler.ContactPolicies.Business.Logic/DTO/ContactPoliciesSettingsDto.cs
  Doppler.ContactPolicies.Business.Logic/Extensions/MapperExtension.cs
  Doppler.ContactPolicies.Business.Logic/Services/ContactPoliciesService.cs
  Doppler.ContactPolicies.Business.Logic/Services/IContactPoliciesService.cs
  Doppler.ContactPolicies.Data.Access/Doppler.ContactPolicies.Data.Access.csproj
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/ContactPoliciesSettingsRepository.cs
  Doppler.ContactPolicies.Data.Access/Repositories/ContactPoliciesSettings/IContactPoliciesSettingsRepository.cs
Labels: size/L
